In [81]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from time import sleep

import pandas as pd

In [82]:
# 別途parameter_personal.pyを定義して、そこにUSERNAMEとPASSWORDを定義してください。
import parameter_personal as params
USERNAME = params.USERNAME  # ユーザー名を設定してください
PASSWORD = params.PASSWORD  # パスワードを設定してください

In [87]:
drive_path = r"C:\Users\zeroc\work\PythonTemplate\webscraping\drvier\chromedriver.exe"
service = webdriver.ChromeService(executable_path=drive_path)
options = Options()
options.add_argument("--headless")
driver = webdriver.Chrome(service=service, options=options)
target_url = 'https://alert.shop-bell.com/'

driver.get(target_url)
sleep(1)

login_page = 'https://alert.shop-bell.com/users/login/'

driver.get(login_page)
sleep(1)

username_input = driver.find_element(By.XPATH, "//input[@id='Email']")
username_input.send_keys(USERNAME)
sleep(1)

password_input = driver.find_element(By.XPATH, "//input[@id='Password']")
password_input.send_keys(PASSWORD)
sleep(1)

login_button = driver.find_element(By.XPATH, "//button[@type='submit' and @class='btn']")
login_button.click()
sleep(1)

list_page = 'https://alert.shop-bell.com/users/alert_list/'
driver.get(list_page)
sleep(1)

table = driver.find_element(By.XPATH, "//tbody")

table_data = []
for tr_element in table.find_elements(By.XPATH, ".//tr"):
    data_row = [td.text for td in tr_element.find_elements(By.XPATH, ".//td")]
    table_data.append(data_row)

df = pd.DataFrame(table_data)
# 欠損値があるものは排除
df = df.dropna(how='any')

df

,0,1,2,3,4,5,6,7
1,16296412,カテゴリー：\n本・コミック・雑誌\nタイトル：\nイマジナリー\n著者：\n幾花にいろ\n...,,2022年07月29日 発売,2巻,発売未定,3巻,編集 一覧 削除紙⇔電子 切換え
2,16296401,カテゴリー：\n本・コミック・雑誌\nタイトル：\n野原ひろし 昼メシの流儀\n著者：\n塚...,,2023年06月12日 発売,11巻,2024年05月10日 発売予定,12巻,編集 一覧 削除紙⇔電子 切換え
3,16296384,カテゴリー：\n本・コミック・雑誌\nタイトル：\nシメジ シミュレーション\n著者：\nつ...,,2024年01月26日 発売,5巻,発売未定,完結,編集 一覧 削除紙⇔電子 切換え
4,16296376,カテゴリー：\n本・コミック・雑誌\nタイトル：\n日常\n著者：\nあらゐけいいち\n販売...,,2022年12月26日 発売,11巻,(2029年12月26日頃 発売予想),12巻,編集 一覧 削除紙⇔電子 切換え
5,16296334,カテゴリー：\n本・コミック・雑誌\nタイトル：\nよふかしのうた\n著者：\nコトヤマ\n...,,2024年03月18日 発売,20巻,発売未定,完結,編集 一覧 削除紙⇔電子 切換え
6,15656140,カテゴリー：\n本・コミック・雑誌\nタイトル：\nONE PIECE\n著者：\n尾田栄一...,,2024年03月04日 発売,108巻,(2024年07月05日頃 発売予想),109巻,編集 一覧 削除紙⇔電子 切換え
7,15656114,カテゴリー：\n本・コミック・雑誌\nタイトル：\nワンナイト・モーニング\n著者：\n奥山...,,2023年12月11日 発売,10巻,2024年04月22日 発売予定,11巻,編集 一覧 削除紙⇔電子 切換え
8,15651054,カテゴリー：\n本・コミック・雑誌\nタイトル：\n喰う寝るふたり 住むふたり 続\n著者：...,,2023年08月19日 発売,5巻,発売未定,完結,編集 一覧 削除紙⇔電子 切換え
9,15566233,カテゴリー：\n本・コミック・雑誌\nタイトル：\n進撃のえろ子さん～変なお姉さんは男子高生...,,2024年02月29日 発売,7巻,(2024年12月01日頃 発売予想),8巻,編集 一覧 削除紙⇔電子 切換え
10,15561791,カテゴリー：\n本・コミック・雑誌\nタイトル：\n映像研には手を出すな!\n著者：\n大童...,,2023年07月12日 発売,8巻,(2024年07月11日頃 発売予想),9巻,編集 一覧 削除紙⇔電子 切換え
11,15561785,カテゴリー：\n本・コミック・雑誌\nタイトル：\n働かないふたり\n著者：\n吉田覚\n販...,,2024年04月09日 発売,31巻,(2024年08月10日頃 発売予想),32巻,編集 一覧 削除紙⇔電子 切換え
12,15561779,カテゴリー：\n本・コミック・雑誌\nタイトル：\n古見さんは、コミュ症です\n著者：\nオ...,,2024年04月17日 発売,33巻,(2024年07月16日頃 発売予想),34巻,編集 一覧 削除紙⇔電子 切換え
13,15370413,カテゴリー：\n本・コミック・雑誌\nタイトル：\nここは今から倫理です。\n著者：\n雨瀬...,,2023年08月18日 発売,8巻,2024年05月17日 発売予定,9巻,編集 一覧 削除紙⇔電子 切換え
14,15065740,カテゴリー：\n本・コミック・雑誌\nタイトル：\nざんげ飯\n著者：\nこだまはつみ\n販...,,2023年02月08日 発売,7巻,発売未定,完結,編集 一覧 削除紙⇔電子 切換え
15,14623033,カテゴリー：\n本・コミック・雑誌\nタイトル：\nこういうのがいい\n著者：\n双龍\n販...,,2023年11月17日 発売,7巻,2024年05月17日 発売予定,8巻,編集 一覧 削除紙⇔電子 切換え
16,14562520,カテゴリー：\n本・コミック・雑誌\nタイトル：\n変女～変な女子高生 甘栗千子～\n著者：...,,2023年09月29日 発売,18巻,(2024年07月01日頃 発売予想),19巻,編集 一覧 削除紙⇔電子 切換え
17,14542513,カテゴリー：\n本・コミック・雑誌\nタイトル：\n波よ聞いてくれ\n著者：\n沙村広明\n...,,2023年04月21日 発売,10巻,2024年04月23日 発売予定,11巻,編集 一覧 削除紙⇔電子 切換え
18,14527696,カテゴリー：\n本・コミック・雑誌\nタイトル：\nその着せ替え人形は恋をする\n著者：\n...,,2023年09月25日 発売,12巻,2024年05月24日 発売予定,13巻,編集 一覧 削除紙⇔電子 切換え
19,14527693,カテゴリー：\n本・コミック・雑誌\nタイトル：\nふらいんぐうぃっち\n著者：\n石塚千尋...,,2023年06月08日 発売,12巻,2024年06月07日 発売予定,13巻,編集 一覧 削除紙⇔電子 切換え
20,14341670,カテゴリー：\n本・コミック・雑誌\nタイトル：\n焼いてるふたり\n著者：\nハナツカシオ...,,2024年03月22日 発売,14巻,2024年06月21日 発売予定,15巻,編集 一覧 削除紙⇔電子 切換え
21,14191473,カテゴリー：\n本・コミック・雑誌\nタイトル：\n魔法使いの嫁\n著者：\nヤマザキコレ\...,,2024年04月12日 発売,20巻,(2024年05月18日頃 発売予想),21巻,編集 一覧 削除紙⇔電子 切換え
22,14191471,カテゴリー：\n本・コミック・雑誌\nタイトル：\n凪のお暇\n著者：\nコナリミサト\n販...,,2024年02月16日 発売,11巻,(2025年08月18日頃 発売予想),12巻,編集 一覧 削除紙⇔電子 切換え
23,14191468,カテゴリー：\n本・コミック・雑誌\nタイトル：\n小森さんは断れない!\n著者：\nクール...,,2023年05月06日 発売,11巻,2024年05月07日 発売予定,12巻,編集 一覧 削除紙⇔電子 切換え
24,14191464,カテゴリー：\n本・コミック・雑誌\nタイトル：\n宇崎ちゃんは遊びたい!\n著者：\n丈\...,,2023年12月08日 発売,11巻,(2024年09月07日頃 発売予想),12巻,編集 一覧 削除紙⇔電子 切換え
25,14191463,"カテゴリー：\n本・コミック・雑誌\nタイトル：\nアルスラーン戦記\n著者：\n荒川弘,田...",,2024年01月09日 発売,20巻,(2024年08月11日頃 発売予想),21巻,編集 一覧 削除紙⇔電子 切換え
26,14191462,カテゴリー：\n本・コミック・雑誌\nタイトル：\nGIANT KILLING\n著者：\n...,,2024年03月22日 発売,63巻,(2024年07月21日頃 発売予想),64巻,編集 一覧 削除紙⇔電子 切換え
27,14191461,カテゴリー：\n本・コミック・雑誌\nタイトル：\nよつばと!\n著者：\nあずまきよひこ\...,,2021年02月27日 発売,15巻,発売未定,16巻,編集 一覧 削除紙⇔電子 切換え
28,14191460,カテゴリー：\n本・コミック・雑誌\nタイトル：\nカッコウの許嫁\n著者：\n吉河美希\n...,,2024年04月17日 発売,22巻,(2024年06月17日頃 発売予想),23巻,編集 一覧 削除紙⇔電子 切換え
29,14191459,カテゴリー：\n本・コミック・雑誌\nタイトル：\n君は放課後インソムニア\n著者：\nオジ...,,2023年10月12日 発売,14巻,発売未定,完結,編集 一覧 削除紙⇔電子 切換え
30,14191449,カテゴリー：\n本・コミック・雑誌\nタイトル：\nてんぷる\n著者：\n吉岡公威\n販売/...,,2024年04月05日 発売,11巻,(2024年10月05日頃 発売予想),12巻,編集 一覧 削除紙⇔電子 切換え
31,14191447,"カテゴリー：\n本・コミック・雑誌\nタイトル：\nぐらんぶる\n著者：\n吉岡公威,井上堅...",,2024年04月05日 発売,22巻,(2024年10月05日頃 発売予想),23巻,編集 一覧 削除紙⇔電子 切換え
32,14191445,カテゴリー：\n本・コミック・雑誌\nタイトル：\n宇宙兄弟\n著者：\n小山宙哉\n販売/...,,2023年09月22日 発売,43巻,(2024年06月22日頃 発売予想),44巻,編集 一覧 削除紙⇔電子 切換え

In [88]:
df_result = pd.DataFrame(columns=['title','num_turns','num_turns_next','release','release_next','status'])
df_result

Empty DataFrame
Columns: [title, num_turns, num_turns_next, release, release_next, status]
Index: []

In [91]:
# タイトル抽出
import re
def cransed_title(title: str) -> str:
    ret = ''
    match = re.search(r'タイトル：\n(.*?)\n著者：', title)
    if match:
        ret = match.group(1)
    else:
        ret = 'Error: cransed_title'
    return ret

In [99]:
# 発売日データ型変更
rnum = df.iloc[1,3]
rnum

'2023年06月12日 発売'

In [105]:
import datetime
def change_datatime(date_str):
    date_pattern = r"(\d{4})年(\d{1,2})月(\d{1,2})日"  # Capture year, month, and day
    expected_pattern = r"\((\d{4})年(\d{1,2})月(\d{1,2})日頃\)"  # Capture expected release date
    
    # Match against the date pattern
    date_match = re.search(date_pattern, date_str)
    expected_match = re.search(expected_pattern, date_str)

    if date_match:
        year = int(date_match.group(1))
        month = int(date_match.group(2))
        day = int(date_match.group(3))

        release_date = f"{year}-{month:02}-{day:02}"

    elif expected_match:
        expected_year = int(expected_match.group(1))
        expected_month = int(expected_match.group(2))
        expected_day = int(expected_match.group(3))

        release_date = f"{expected_year}-{expected_month:02}-{expected_day:02}"

    else:
        release_date = ''
        print("Invalid date format")

    return release_date

rc = change_datatime(rnum)
rc

'2023-06-12'

In [109]:
# df_result = pd.DataFrame(columns=['title','num_turns','num_turns_next','release','release_next','status'])
# 1:title, 3:release, 4:巻数, 5:release_next, 6:巻数_next,
# Noneが入らないように注意すること
df_result['title'] = df[1].apply(cransed_title)
df_result['release'] = df[3].apply(change_datatime)
df_result['num_turns'] = df[4]
df_result['release_next'] = df[5].apply(change_datatime)
df_result['num_turns_next'] = df[6]
df_result

Invalid date format
Invalid date format
Invalid date format
Invalid date format
Invalid date format
Invalid date format
Invalid date format

,title,num_turns,num_turns_next,release,release_next,status
1,イマジナリー,2巻,3巻,2022-07-29,,NaN
2,野原ひろし 昼メシの流儀,11巻,12巻,2023-06-12,2024-05-10,NaN
3,シメジ シミュレーション,5巻,完結,2024-01-26,,NaN
4,日常,11巻,12巻,2022-12-26,2029-12-26,NaN
5,よふかしのうた,20巻,完結,2024-03-18,,NaN
6,ONE PIECE,108巻,109巻,2024-03-04,2024-07-05,NaN
7,ワンナイト・モーニング,10巻,11巻,2023-12-11,2024-04-22,NaN
8,喰う寝るふたり 住むふたり 続,5巻,完結,2023-08-19,,NaN
9,進撃のえろ子さん～変なお姉さんは男子高生と仲良くなりたい～,7巻,8巻,2024-02-29,2024-12-01,NaN
10,映像研には手を出すな!,8巻,9巻,2023-07-12,2024-07-11,NaN
11,働かないふたり,31巻,32巻,2024-04-09,2024-08-10,NaN
12,古見さんは、コミュ症です,33巻,34巻,2024-04-17,2024-07-16,NaN
13,ここは今から倫理です。,8巻,9巻,2023-08-18,2024-05-17,NaN
14,ざんげ飯,7巻,完結,2023-02-08,,NaN
15,こういうのがいい,7巻,8巻,2023-11-17,2024-05-17,NaN
16,変女～変な女子高生 甘栗千子～,18巻,19巻,2023-09-29,2024-07-01,NaN
17,波よ聞いてくれ,10巻,11巻,2023-04-21,2024-04-23,NaN
18,その着せ替え人形は恋をする,12巻,13巻,2023-09-25,2024-05-24,NaN
19,ふらいんぐうぃっち,12巻,13巻,2023-06-08,2024-06-07,NaN
20,焼いてるふたり,14巻,15巻,2024-03-22,2024-06-21,NaN
21,魔法使いの嫁,20巻,21巻,2024-04-12,2024-05-18,NaN
22,凪のお暇,11巻,12巻,2024-02-16,2025-08-18,NaN
23,小森さんは断れない!,11巻,12巻,2023-05-06,2024-05-07,NaN
24,宇崎ちゃんは遊びたい!,11巻,12巻,2023-12-08,2024-09-07,NaN
25,アルスラーン戦記,20巻,21巻,2024-01-09,2024-08-11,NaN
26,GIANT KILLING,63巻,64巻,2024-03-22,2024-07-21,NaN
27,よつばと!,15巻,16巻,2021-02-27,,NaN
28,カッコウの許嫁,22巻,23巻,2024-04-17,2024-06-17,NaN
29,君は放課後インソムニア,14巻,完結,2023-10-12,,NaN
30,てんぷる,11巻,12巻,2024-04-05,2024-10-05,NaN
31,ぐらんぶる,22巻,23巻,2024-04-05,2024-10-05,NaN
32,宇宙兄弟,43巻,44巻,2023-09-22,2024-06-22,NaN